apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: digital-lommebok-oauth-server
  description: EUDIWs OAuth2-server
  annotations:
    github.com/project-slug: felleslosninger/eudiw-oauth-server
spec:
  type: application
  lifecycle: production
  owner: team-digital-lommebok
  system: digital-lommebok
  dependsOn:
    - component:idporten-login
    - component:idporten-c2id-server
