name: eudiw-oauth-server
networks:
  eudiw:
    name: eudiw

services:
  eudiw-oauth-server:
    build:
      context: .
      dockerfile: docker/dev.Dockerfile
      args:
        GIT_PACKAGE_TOKEN: ${GIT_PACKAGE_TOKEN}
        GIT_PACKAGE_USERNAME: ${GIT_PACKAGE_USERNAME}
    environment:
      spring_profiles_active: docker
      _JAVA_OPTIONS: "-XX:+IgnoreUnrecognizedVMOptions -XX:UseSVE=0"
    env_file:
        - .env
    ports:
      - "9260:9260"
      - "9261:9261"
      - "9262:9262"
    networks:
      - eudiw
    entrypoint: "/bin/bash -c"
    command:
      - |
        cd /usr/local/tomcat/webapps/
        java -javaagent:opentelemetry-javaagent.jar -agentlib:jdwp=transport=dt_socket,server=y,suspend=n,address=*:9262 -jar application.jar
    healthcheck:
      test: wget --no-verbose --tries=1 --spider http://localhost:9261/health/readiness || exit 1
      interval: 15s
      start_period: 5s
      timeout: 5s
      retries: 20
