---
server:
  port: 9260
  servlet:
    session:
      cookie:
        secure: false

management:
  server:
    port: 9261
  endpoint:
    health:
      show-details: always
spring:
  config:
    import: file:.env[.properties]
  application:
    environment: dev
  data:
    redis:
      port: 9262
      host: localhost

# EUDIW auth server
oauth-authorization-server:
  issuer: http://digital-lommebok-oauth-server:9260
  scopes-supported:
    - foo
    - bar
oidc-proxy:
  redirect-uri: ${oauth-authorization-server.issuer}/callback
  oidc-issuer:
    issuer: https://idporten.dev
    authorization-endpoint: https://login.idporten.dev/authorize
