---
server:
  port: 8080

spring:
  thread-executor: virtual
  application:
    name: eudiw-oauth-server
    environment: default

# Spring Boot Actuator
management:
  server:
    port: 8090
  endpoints:
    web:
      exposure:
        include: info,version,prometheus,health
      base-path: /
  endpoint:
    health:
      probes:
        enabled: true
  metrics:
    tags:
      application: ${spring.application.name}
      environment: ${spring.application.environment}

# Digdir standard logging
digdir:
  access:
    logging:
      debug-level: request
      filtering:
        static-resources: true
  audit:
    log-dir:
    log-file:
    application-name: ${spring.application.name}
    application-environment: ${spring.application.environment}
    filters:
      admin-header: false
      bearer-token: false
      correlation-id: false
      ip-address: true
    prometheus:
      counter: true

# EUDIW oAuth proxy
oauth-authorization-server:
  keystore:
    type: ${TOKEN_SIGNING_KEYSTORE_TYPE}
    location: ${TOKEN_SIGNING_KEYSTORE_LOCATION}
    password: ${TOKEN_SIGNING_KEYSTORE_PASSWORD}
    key-alias: ${TOKEN_SIGNING_KEYSTORE_KEY_ALIAS}
    key-password: ${TOKEN_SIGNING_KEYSTORE_KEY_PASSORD}
  grant-types-supported:
    - authorization_code
    - urn:ietf:params:oauth:grant-type:pre-authorized_code
