---
server:
  port: 9260

management:
  server:
    port: 9261
  endpoint:
    health:
      show-details: always
spring:
  config:
    import: file:.env[.properties]
  application:
    environment: dev
  
