---
server:
  port: 9260

management:
  server:
    port: 9261
  endpoint:
    health:
      show-details: always

spring:
  application:
    environment: docker

# EUDIW auth server
oauth-authorization-server:
  issuer: http://digital-lommebok-oauth-server:9260
  scopes-supported:
    - foo
    - bar
