# This workflow will build a Java project with Maven.
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-maven

name: Testing maven build

on:
  pull_request:
    branches: [ main ]
    paths-ignore:
      - 'src/test/**'
      - 'docker/**'
      - 'docker-compose.yaml'
      - '*.md'
      - 'LICENSE'

jobs:
  call-workflow-maven-build:
    uses: felleslosninger/github-workflows/.github/workflows/ci-maven-build.yml@main
    with:
      java-version: 24
    secrets: inherit
  call-container-scan:
    uses: felleslosninger/github-workflows/.github/workflows/ci-spring-boot-container-scan.yml@main
    with:
      image-name: eudiw-oauth-server
      java-version: 24
    secrets: inherit
