# See https://github.com/felleslosninger/github-workflows for reusable workflow used.

name: On PR label

on:
  pull_request:
    types: [labeled]

jobs:
  on-pr-label:
    uses: felleslosninger/github-workflows/.github/workflows/on-pr-label.yml@main
